# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getAudioDevicesCpp <- function() {
    .Call(`_sdlr_getAudioDevicesCpp`)
}

makeSDLAUDIO <- function(file) {
    .Call(`_sdlr_makeSDLAUDIO`, file)
}

makeSDLAUDIOint <- function(file, idx_dev) {
    .Call(`_sdlr_makeSDLAUDIOint`, file, idx_dev)
}

makeSDLAUDIOstring <- function(file, devname) {
    .Call(`_sdlr_makeSDLAUDIOstring`, file, devname)
}

clearSDLAUDIO <- function(ptr) {
    invisible(.Call(`_sdlr_clearSDLAUDIO`, ptr))
}

getstatusSDLAUDIO <- function(ptr) {
    .Call(`_sdlr_getstatusSDLAUDIO`, ptr)
}

pauseSDLAUDIO <- function(ptr) {
    invisible(.Call(`_sdlr_pauseSDLAUDIO`, ptr))
}

unpauseSDLAUDIO <- function(ptr) {
    invisible(.Call(`_sdlr_unpauseSDLAUDIO`, ptr))
}

queueSDLAUDIO <- function(ptr) {
    invisible(.Call(`_sdlr_queueSDLAUDIO`, ptr))
}

