# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pick_point_raw <- function(vec, width, height, colfmt, chorder = "cxy", title = "", x = 0L, y = 0L, renderer_idx = -1L, n = 1L, mark = TRUE, size = 5L, color = as.numeric( c(0,0,0,255)), max_count = -1L) {
    .Call(`_sdlr_pick_point_raw`, vec, width, height, colfmt, chorder, title, x, y, renderer_idx, n, mark, size, color, max_count)
}

pick_point_numeric <- function(vec, width, height, colfmt, chorder = "cxy", title = "", x = 0L, y = 0L, renderer_idx = -1L, n = 1L, mark = TRUE, size = 5L, color = as.numeric( c(0,0,0,255)), max_count = -1L) {
    .Call(`_sdlr_pick_point_numeric`, vec, width, height, colfmt, chorder, title, x, y, renderer_idx, n, mark, size, color, max_count)
}

pick_line_raw <- function(vec, width, height, colfmt, chorder = "cxy", title = "", x = 0L, y = 0L, renderer_idx = -1L, n = 1L, mark = TRUE, size = 5L, color = as.numeric( c(0,0,0,255)), max_count = -1L) {
    .Call(`_sdlr_pick_line_raw`, vec, width, height, colfmt, chorder, title, x, y, renderer_idx, n, mark, size, color, max_count)
}

pick_line_numeric <- function(vec, width, height, colfmt, chorder = "cxy", title = "", x = 0L, y = 0L, renderer_idx = -1L, n = 1L, mark = TRUE, size = 5L, color = as.numeric( c(0,0,0,255)), max_count = -1L) {
    .Call(`_sdlr_pick_line_numeric`, vec, width, height, colfmt, chorder, title, x, y, renderer_idx, n, mark, size, color, max_count)
}

pick_rect_raw <- function(vec, width, height, colfmt, chorder = "cxy", title = "", x = 0L, y = 0L, renderer_idx = -1L, n = 1L, mark = TRUE, size = 5L, color = as.numeric( c(0,0,0,255)), max_count = -1L) {
    .Call(`_sdlr_pick_rect_raw`, vec, width, height, colfmt, chorder, title, x, y, renderer_idx, n, mark, size, color, max_count)
}

pick_rect_numeric <- function(vec, width, height, colfmt, chorder = "cxy", title = "", x = 0L, y = 0L, renderer_idx = -1L, n = 1L, mark = TRUE, size = 5L, color = as.numeric( c(0,0,0,255)), max_count = -1L) {
    .Call(`_sdlr_pick_rect_numeric`, vec, width, height, colfmt, chorder, title, x, y, renderer_idx, n, mark, size, color, max_count)
}

getAudioDevicesCpp <- function() {
    .Call(`_sdlr_getAudioDevicesCpp`)
}

makeSDLAUDIO <- function(file) {
    .Call(`_sdlr_makeSDLAUDIO`, file)
}

makeSDLAUDIOint <- function(file, idx_dev) {
    .Call(`_sdlr_makeSDLAUDIOint`, file, idx_dev)
}

makeSDLAUDIOstring <- function(file, devname) {
    .Call(`_sdlr_makeSDLAUDIOstring`, file, devname)
}

deleteSDLAUDIO <- function(ptr) {
    invisible(.Call(`_sdlr_deleteSDLAUDIO`, ptr))
}

clearSDLAUDIO <- function(ptr) {
    invisible(.Call(`_sdlr_clearSDLAUDIO`, ptr))
}

getstatusSDLAUDIO <- function(ptr) {
    .Call(`_sdlr_getstatusSDLAUDIO`, ptr)
}

pauseSDLAUDIO <- function(ptr) {
    invisible(.Call(`_sdlr_pauseSDLAUDIO`, ptr))
}

unpauseSDLAUDIO <- function(ptr) {
    invisible(.Call(`_sdlr_unpauseSDLAUDIO`, ptr))
}

queueSDLAUDIO <- function(ptr) {
    invisible(.Call(`_sdlr_queueSDLAUDIO`, ptr))
}

displaySDLRIMAGEnumeric <- function(vec, width, height, colfmt, chorder = "cxy", title = "", x = 0L, y = 0L, renderer_idx = -1L, max_count = -1L) {
    invisible(.Call(`_sdlr_displaySDLRIMAGEnumeric`, vec, width, height, colfmt, chorder, title, x, y, renderer_idx, max_count))
}

displaySDLRIMAGEraw <- function(vec, width, height, colfmt, chorder = "cxy", title = "", x = 0L, y = 0L, renderer_idx = -1L, max_count = -1L) {
    invisible(.Call(`_sdlr_displaySDLRIMAGEraw`, vec, width, height, colfmt, chorder, title, x, y, renderer_idx, max_count))
}

makeSDLRIMAGEnumeric <- function(vec, width, height, colfmt, chorder = "cxy", title = "", x = 0L, y = 0L, renderer_idx = -1L) {
    .Call(`_sdlr_makeSDLRIMAGEnumeric`, vec, width, height, colfmt, chorder, title, x, y, renderer_idx)
}

makeSDLRIMAGEraw <- function(vec, width, height, colfmt, chorder = "cxy", title = "", x = 0L, y = 0L, renderer_idx = -1L) {
    .Call(`_sdlr_makeSDLRIMAGEraw`, vec, width, height, colfmt, chorder, title, x, y, renderer_idx)
}

makeSDLRIMAGEnumericC <- function(vec, width, height, colfmt, chorder = "cxy", title = "", renderer_idx = -1L) {
    .Call(`_sdlr_makeSDLRIMAGEnumericC`, vec, width, height, colfmt, chorder, title, renderer_idx)
}

makeSDLRIMAGErawC <- function(vec, width, height, colfmt, chorder = "cxy", title = "", renderer_idx = -1L) {
    .Call(`_sdlr_makeSDLRIMAGErawC`, vec, width, height, colfmt, chorder, title, renderer_idx)
}

makeSDLRIMAGEnumericU <- function(vec, width, height, colfmt, chorder = "cxy", title = "", renderer_idx = -1L) {
    .Call(`_sdlr_makeSDLRIMAGEnumericU`, vec, width, height, colfmt, chorder, title, renderer_idx)
}

makeSDLRIMAGErawU <- function(vec, width, height, colfmt, chorder = "cxy", title = "", renderer_idx = -1L) {
    .Call(`_sdlr_makeSDLRIMAGErawU`, vec, width, height, colfmt, chorder, title, renderer_idx)
}

deleteSDLRIMAGE <- function(ptr) {
    invisible(.Call(`_sdlr_deleteSDLRIMAGE`, ptr))
}

replaceSDLRIMAGEraw <- function(ptr, vec, width, height, colfmt, chorder) {
    invisible(.Call(`_sdlr_replaceSDLRIMAGEraw`, ptr, vec, width, height, colfmt, chorder))
}

replaceSDLRIMAGEnumeric <- function(ptr, vec, width, height, colfmt, chorder) {
    invisible(.Call(`_sdlr_replaceSDLRIMAGEnumeric`, ptr, vec, width, height, colfmt, chorder))
}

SDLR_QUIT <- function() {
    invisible(.Call(`_sdlr_SDLR_QUIT`))
}

